[tool.poetry]
name = "hacky-cloud-drive"
version = "0.1.0"
description = ""
authors = ["Micha≈Ç Freliszka <mfreliszka@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "5.1.6"
djangorestframework = "3.15.2"
ruff = "^0.9.9"
uvicorn = "^0.34.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
